<script setup>
import{ref}from'vue';import{onShow}from'@dcloudio/uni-app';import AppHeader from'../../components/AppHeader.vue';import BottomNav from'../../components/BottomNav.vue';import{api}from'../../api'
const profile=ref(uni.getStorageSync('userProfile')||{}),shop=ref({});onShow(async()=>{try{const [user,shopData]=await Promise.all([api.userProfile(),api.shop()]);profile.value=user;shop.value=shopData;uni.setStorageSync('userProfile',user)}catch(_){}})
function edit(){uni.showModal({title:'修改昵称',editable:true,placeholderText:'请输入昵称',content:profile.value.nickname||'',success:async res=>{if(res.confirm&&res.content?.trim()){profile.value=await api.updateUserProfile({nickname:res.content.trim()});uni.setStorageSync('userProfile',profile.value)}}})}
function call(){if(shop.value.phone)uni.makePhoneCall({phoneNumber:shop.value.phone})}
async function logout(){uni.showModal({title:'退出登录',content:'确定退出当前账号吗？',success:async res=>{if(res.confirm){try{await api.userLogout()}catch(_){}uni.removeStorageSync('userToken');uni.removeStorageSync('userProfile');uni.reLaunch({url:'/pages/login/index'})}}})}
</script>
<template><view class="page page-with-nav"><view class="hero"><AppHeader title="我的"/><view class="user-card"><view class="avatar">{{profile.nickname?.slice(0,1)||'食'}}</view><view><text class="name">{{profile.nickname||'微信用户'}}</text><text class="muted">{{profile.phone||'完善手机号，联系更方便'}}</text></view><text class="edit" @tap="edit">编辑 ›</text></view></view><view class="content"><view class="card order-entry" @tap="uni.redirectTo({url:'/pages/orders/index'})"><view><text class="section-title">我的订单</text><text class="muted">查看全部订单</text></view><text>›</text></view><view class="card menu"><view @tap="uni.navigateTo({url:'/pages/addresses/index'})"><text>⌖</text><text>收货地址</text><text>›</text></view><view @tap="call"><text>☎</text><text>联系商家</text><text>›</text></view><view @tap="uni.navigateTo({url:'/pages/merchant/login'})"><text>▦</text><text>商家端入口</text><text>›</text></view></view><button class="logout" @tap="logout">退出登录</button></view><BottomNav active="profile"/></view></template>
<style scoped>.hero{padding-bottom:30rpx;background:linear-gradient(160deg,#fff5e9,#fff)}.user-card{display:flex;align-items:center;gap:22rpx;margin:16rpx 30rpx;padding:28rpx;border-radius:24rpx;background:#fff;box-shadow:0 8rpx 30rpx rgba(255,138,52,.09)}.avatar{width:100rpx;height:100rpx;border-radius:50%;background:#ff8a34;color:#fff;text-align:center;line-height:100rpx;font-size:42rpx;font-weight:800}.user-card>view:nth-child(2){flex:1;display:flex;flex-direction:column;gap:10rpx}.name{font-size:33rpx;font-weight:800}.edit{color:#999;font-size:24rpx}.order-entry{padding:28rpx;display:flex;align-items:center;justify-content:space-between}.order-entry>view{display:flex;flex-direction:column;gap:8rpx}.menu{margin-top:22rpx;padding:0 28rpx}.menu view{height:100rpx;display:flex;align-items:center;gap:22rpx;border-bottom:2rpx solid #f1f1f1}.menu view:last-child{border:0}.menu view text:nth-child(2){flex:1}.menu view text:last-child{color:#aaa;font-size:38rpx}.logout{margin-top:30rpx;height:84rpx;border-radius:42rpx;background:#fff;color:#ff4d4f;font-size:27rpx;line-height:84rpx}</style>
