<script setup>
import{ref}from'vue';import{onShow}from'@dcloudio/uni-app';import{api}from'../../api'
const list=ref([]),show=ref(false),editingId=ref(null);const emptyForm=()=>({contactName:'',gender:null,phone:'',area:'',detail:'',houseNumber:'',tag:'家',isDefault:false});const form=ref(emptyForm())
onShow(load);async function load(){try{list.value=await api.addresses()}catch(_){}}
function edit(item){editingId.value=item?.id||null;form.value=item?{...item}:emptyForm();show.value=true}
async function save(){if(!form.value.contactName.trim()||!/^1[3-9]\d{9}$/.test(form.value.phone)||!form.value.area.trim()||!form.value.detail.trim())return uni.showToast({title:'请完整填写联系人、手机号和地址',icon:'none'});try{if(editingId.value)await api.updateAddress(editingId.value,form.value);else await api.createAddress(form.value);show.value=false;await load();uni.showToast({title:'保存成功'})}catch(_){}}
async function setDefault(item){await api.defaultAddress(item.id);await load()}
function remove(item){uni.showModal({title:'删除地址',content:'确定删除这个收货地址吗？',success:async res=>{if(res.confirm){await api.deleteAddress(item.id);await load()}}})}
</script>
<template><view class="page address-page"><view class="content"><view v-for="item in list" :key="item.id" class="card address"><view class="between"><view><text class="name">{{item.contactName}}</text><text class="phone">{{item.phone}}</text><text v-if="item.tag" class="tag">{{item.tag}}</text><text v-if="item.isDefault" class="default">默认</text></view><text class="edit" @tap="edit(item)">编辑</text></view><text class="detail">{{item.area}}{{item.detail}}{{item.houseNumber||''}}</text><view class="actions"><text v-if="!item.isDefault" @tap="setDefault(item)">设为默认</text><text @tap="remove(item)">删除</text></view></view><view v-if="!list.length" class="empty"><text class="empty-icon">⌖</text>还没有收货地址</view></view><view class="add-bar"><button class="primary-btn" @tap="edit(null)">＋ 新增收货地址</button></view><view v-if="show" class="mask" @tap.self="show=false"><view class="sheet"><view class="between title"><text>{{editingId?'编辑地址':'新增地址'}}</text><text @tap="show=false">×</text></view><view class="field"><text class="field-label">联系人</text><input v-model="form.contactName" class="input" placeholder="请输入联系人姓名"/></view><view class="field"><text class="field-label">联系电话</text><input v-model="form.phone" class="input" type="number" maxlength="11" placeholder="请输入手机号"/></view><view class="field"><text class="field-label">所在区域</text><input v-model="form.area" class="input" placeholder="例如：上海市浦东新区"/></view><view class="field"><text class="field-label">详细地址</text><input v-model="form.detail" class="input" placeholder="街道、小区、楼栋"/></view><view class="field"><text class="field-label">门牌号</text><input v-model="form.houseNumber" class="input" placeholder="例如：2栋1203室"/></view><view class="field"><text class="field-label">地址标签</text><view class="tags"><text v-for="tag in ['家','公司','学校']" :key="tag" :class="{active:form.tag===tag}" @tap="form.tag=tag">{{tag}}</text></view></view><view class="default-row between" @tap="form.isDefault=!form.isDefault"><text>设为默认地址</text><switch color="#ff8a34" :checked="form.isDefault" @change="form.isDefault=$event.detail.value"/></view><button class="primary-btn" @tap="save">保存地址</button></view></view></view></template>
<style scoped>.address-page{padding-bottom:130rpx}.address{padding:28rpx;margin-bottom:20rpx}.name{font-size:30rpx;font-weight:800}.phone{margin-left:18rpx;color:#666}.tag,.default{margin-left:12rpx;padding:4rpx 12rpx;border-radius:8rpx;background:#fff2e8;color:#ff8a34;font-size:20rpx}.default{background:#f6ffed;color:#34c759}.edit{color:#ff8a34}.detail{display:block;margin-top:18rpx;font-size:27rpx;line-height:1.5}.actions{display:flex;justify-content:flex-end;gap:30rpx;margin-top:20rpx;padding-top:18rpx;border-top:2rpx solid #f2f2f2;color:#999;font-size:23rpx}.add-bar{position:fixed;left:0;right:0;bottom:0;padding:16rpx 28rpx calc(16rpx + env(safe-area-inset-bottom));background:#fff}.add-bar button{width:100%}.mask{position:fixed;z-index:100;inset:0;display:flex;align-items:flex-end;background:rgba(0,0,0,.5)}.sheet{width:100%;max-height:92vh;overflow:auto;padding:30rpx 30rpx calc(30rpx + env(safe-area-inset-bottom));border-radius:32rpx 32rpx 0 0;background:#fff}.title{margin-bottom:30rpx;font-size:34rpx;font-weight:800}.title text:last-child{font-size:48rpx;font-weight:400}.tags{display:flex;gap:18rpx}.tags text{padding:14rpx 30rpx;border-radius:12rpx;background:#f3f3f3}.tags .active{background:#fff2e8;color:#ff8a34}.default-row{padding:14rpx 0 30rpx}.sheet button{width:100%}</style>
