<script setup>
import{computed,ref}from'vue';import{onLoad}from'@dcloudio/uni-app';import ProductImage from'../../components/ProductImage.vue';import StatusBadge from'../../components/StatusBadge.vue';import{api}from'../../api';import{dateTime,money}from'../../utils/format'
const id=ref(),order=ref(null);const isDelivery=computed(()=>order.value?.orderType?.code===2)
onLoad(query=>{id.value=query.id;load()});async function load(){try{order.value=await api.userOrder(id.value)}catch(_){}}
async function cancel(){uni.showModal({title:'取消订单',content:'确定取消这个待接单订单吗？',success:async res=>{if(res.confirm){await api.cancelOrder(id.value);uni.showToast({title:'已取消'});await load()}}})}
async function confirm(){uni.showModal({title:'确认收货',content:'请确认您已经收到餐品',success:async res=>{if(res.confirm){await api.confirmOrder(id.value);uni.showToast({title:'订单已完成'});await load()}}})}
function call(){if(order.value.contactPhone)uni.makePhoneCall({phoneNumber:order.value.contactPhone})}
</script>
<template><view v-if="order" class="page detail-page"><view class="status-card" :class="isDelivery?'blue':'orange'"><view class="between"><view><text class="status-title">{{order.status.description}}</text><text class="status-tip">{{order.status.code===1?'商家正在确认订单，请稍候':order.status.code===3?'餐品正在制作中':order.status.code===5?'商家正在配送中，请保持电话畅通':'感谢您的耐心等待'}}</text></view><StatusBadge :status="order.status"/></view><view class="timeline"><view v-for="log in order.statusLogs" :key="log.orderVersion"><text class="dot"></text><text>{{log.toStatus.description}}</text></view></view></view><view class="content"><view class="card info-card"><text class="section-title">{{isDelivery?'收货信息':'就餐信息'}}</text><view class="info"><text>联系人</text><text>{{order.contactName}} {{order.contactPhone}}</text></view><view v-if="isDelivery" class="info"><text>收货地址</text><text>{{order.addressArea}}{{order.addressDetail}}{{order.addressHouseNumber}}</text></view><view v-else class="info"><text>桌号</text><text>{{order.noSeatYet?'暂未入座':order.tableNo}}</text></view><view v-if="isDelivery" class="info"><text>配送方式</text><text>商家配送</text></view></view><view class="card goods-card"><text class="section-title">商品清单</text><view v-for="item in order.items" :key="item.id" class="goods"><ProductImage :src="item.productImageUrl" :name="item.productName" size="90rpx"/><view><text>{{item.productName}}</text><small>{{[item.specificationName,item.tasteName].filter(Boolean).join(' · ')}}</small></view><text>×{{item.quantity}}</text><text>¥{{money(item.amount)}}</text></view></view><view class="card fee-card"><view class="between"><text>商品总额</text><text>¥{{money(order.totalAmount)}}</text></view><view class="between"><text>包装费</text><text>¥{{money(order.packageFee)}}</text></view><view v-if="isDelivery" class="between"><text>配送费</text><text>¥{{money(order.deliveryFee)}}</text></view><view class="divider"></view><view class="between pay"><text>实付金额</text><text class="price">¥{{money(order.payAmount)}}</text></view></view><view class="card order-info"><text class="section-title">订单信息</text><view class="info"><text>订单号</text><text>{{order.orderNo}}</text></view><view class="info"><text>下单时间</text><text>{{dateTime(order.createTime)}}</text></view><view v-if="order.remark" class="info"><text>备注</text><text>{{order.remark}}</text></view><view v-if="order.rejectReason" class="info"><text>拒单原因</text><text>{{order.rejectReason}}</text></view></view></view><view class="actions"><button class="outline-btn" @tap="call">联系商家</button><button v-if="order.status.code===1" class="outline-btn danger-outline" @tap="cancel">取消订单</button><button v-if="isDelivery&&order.status.code===6" class="primary-btn" @tap="confirm">确认收货</button></view></view>
</template>
<style scoped>.detail-page{padding-bottom:130rpx}.status-card{margin:24rpx 28rpx;padding:28rpx;border-radius:24rpx}.orange{background:linear-gradient(135deg,#fff7ed,#fff0df)}.blue{background:linear-gradient(135deg,#eef9ff,#e6f4ff)}.status-title{display:block;font-size:36rpx;font-weight:800}.status-tip{display:block;margin-top:10rpx;color:#777;font-size:22rpx}.timeline{display:flex;gap:12rpx;margin-top:26rpx;overflow:hidden}.timeline view{display:flex;align-items:center;gap:6rpx;color:#777;font-size:20rpx;white-space:nowrap}.dot{width:13rpx;height:13rpx;border-radius:50%;background:#ff8a34}.card{padding:28rpx;margin-bottom:22rpx}.section-title{display:block;margin-bottom:18rpx}.info{display:flex;justify-content:space-between;gap:30rpx;padding:15rpx 0;color:#666;font-size:24rpx}.info text:last-child{max-width:65%;text-align:right;color:#222}.goods{display:flex;align-items:center;gap:14rpx;padding:17rpx 0;border-top:2rpx solid #f3f3f3;font-size:23rpx}.goods>view{min-width:0;flex:1;display:flex;flex-direction:column}.goods small{margin-top:6rpx;color:#999}.fee-card .between{margin:18rpx 0;font-size:24rpx}.pay{font-weight:700}.actions{position:fixed;z-index:50;left:0;right:0;bottom:0;height:calc(112rpx + env(safe-area-inset-bottom));padding:16rpx 28rpx calc(16rpx + env(safe-area-inset-bottom));display:flex;justify-content:flex-end;gap:14rpx;background:#fff;border-top:2rpx solid #eee}.actions .primary-btn{width:240rpx}.actions .outline-btn{width:auto}</style>
