import { request } from './request'

export const api = {
  shop: () => request({ url: '/api/common/shop', hideLoading: true }),
  categories: () => request({ url: '/api/user/categories', hideLoading: true }),
  products: (data = {}) => request({ url: '/api/user/products', data, hideLoading: true }),
  product: id => request({ url: `/api/user/products/${id}` }),
  userLogin: code => request({ url: '/api/user/auth/wechat-login', method: 'POST', data: { code } }),
  userLogout: () => request({ url: '/api/user/auth/logout', method: 'POST' }),
  userProfile: () => request({ url: '/api/user/profile' }),
  updateUserProfile: data => request({ url: '/api/user/profile', method: 'PUT', data }),
  cart: () => request({ url: '/api/user/cart', hideLoading: true }),
  addCart: data => request({ url: '/api/user/cart/items', method: 'POST', data }),
  updateCart: (id, quantity) => request({ url: `/api/user/cart/items/${id}`, method: 'PUT', data: { quantity } }),
  deleteCart: id => request({ url: `/api/user/cart/items/${id}`, method: 'DELETE' }),
  clearCart: () => request({ url: '/api/user/cart/items', method: 'DELETE' }),
  addresses: () => request({ url: '/api/user/addresses' }),
  createAddress: data => request({ url: '/api/user/addresses', method: 'POST', data }),
  updateAddress: (id, data) => request({ url: `/api/user/addresses/${id}`, method: 'PUT', data }),
  defaultAddress: id => request({ url: `/api/user/addresses/${id}/default`, method: 'PUT' }),
  deleteAddress: id => request({ url: `/api/user/addresses/${id}`, method: 'DELETE' }),
  createOrder: (data, key) => request({ url: '/api/user/orders', method: 'POST', data, header: { 'Idempotency-Key': key } }),
  userOrders: (data = {}) => request({ url: '/api/user/orders', data, hideLoading: true }),
  userOrder: id => request({ url: `/api/user/orders/${id}` }),
  cancelOrder: id => request({ url: `/api/user/orders/${id}/cancel`, method: 'PUT' }),
  confirmOrder: id => request({ url: `/api/user/orders/${id}/confirm-receipt`, method: 'PUT' }),
  merchantLogin: data => request({ url: '/api/merchant/auth/login', method: 'POST', data }),
  merchantLogout: () => request({ url: '/api/merchant/auth/logout', method: 'POST' }),
  merchantProfile: () => request({ url: '/api/merchant/profile' }),
  changePassword: data => request({ url: '/api/merchant/password', method: 'PUT', data }),
  dashboard: () => request({ url: '/api/merchant/dashboard', hideLoading: true }),
  merchantOrders: (data = {}) => request({ url: '/api/merchant/orders', data, hideLoading: true }),
  merchantOrder: id => request({ url: `/api/merchant/orders/${id}` }),
  orderAction: (id, action, data) => request({ url: `/api/merchant/orders/${id}/${action}`, method: 'PUT', data }),
  merchantCategories: () => request({ url: '/api/merchant/categories' }),
  merchantProducts: (data = {}) => request({ url: '/api/merchant/products', data, hideLoading: true }),
  merchantProduct: id => request({ url: `/api/merchant/products/${id}` }),
  saveProduct: (data, id) => request({ url: id ? `/api/merchant/products/${id}` : '/api/merchant/products', method: id ? 'PUT' : 'POST', data }),
  productAction: (id, action) => request({ url: `/api/merchant/products/${id}/${action}`, method: 'PUT' }),
  deleteProduct: id => request({ url: `/api/merchant/products/${id}`, method: 'DELETE' }),
  merchantShop: () => request({ url: '/api/merchant/shop' }),
  updateShop: data => request({ url: '/api/merchant/shop', method: 'PUT', data }),
  shopStatus: (path, data) => request({ url: `/api/merchant/shop/${path}`, method: 'PUT', data }),
}
