<script setup>
import{ref}from'vue';import{onPullDownRefresh,onShow}from'@dcloudio/uni-app';import AppHeader from'../../components/AppHeader.vue';import BottomNav from'../../components/BottomNav.vue';import OrderCard from'../../components/OrderCard.vue';import{api}from'../../api';import{money}from'../../utils/format'
const shop=ref({}),stats=ref({}),orders=ref([])
onShow(load);onPullDownRefresh(async()=>{await load();uni.stopPullDownRefresh()});async function load(){try{const [shopData,dashboard,orderData]=await Promise.all([api.merchantShop(),api.dashboard(),api.merchantOrders({current:1,size:5,status:1})]);shop.value=shopData;stats.value=dashboard;orders.value=orderData?.records||[]}catch(_){}}
async function toggle(path,value){try{shop.value=await api.shopStatus(path,path==='business-status'?{status:value?1:0}:{enabled:value})}catch(_){}}
function open(order){uni.navigateTo({url:`/pages/merchant/order-detail?id=${order.id}`})}
</script>
<template><view class="page page-with-nav"><AppHeader :title="shop.name||'食刻小馆'" subtitle="商家工作台"><view class="business"><text>{{shop.businessStatus?.description}}</text><switch color="#34c759" :checked="shop.businessStatus?.code===1" @change="toggle('business-status',$event.detail.value)"/></view></AppHeader><view class="content"><view class="date">今日经营概览</view><view class="overview"><view><text>今日订单</text><strong>{{stats.todayOrderCount||0}}</strong></view><view><text>今日营业额</text><strong>¥{{money(stats.todayTurnover)}}</strong></view></view><view class="status-grid"><view @tap="uni.redirectTo({url:'/pages/merchant/orders?status=1'})"><text class="orange">{{stats.pendingAcceptCount||0}}</text><small>待接单</small></view><view @tap="uni.redirectTo({url:'/pages/merchant/orders?status=3'})"><text class="yellow">{{stats.cookingCount||0}}</text><small>制作中</small></view><view @tap="uni.redirectTo({url:'/pages/merchant/orders?status=4'})"><text class="purple">{{stats.readyForPickupCount||0}}</text><small>堂食待取</small></view><view @tap="uni.redirectTo({url:'/pages/merchant/orders?status=5'})"><text class="cyan">{{stats.deliveringCount||0}}</text><small>配送中</small></view></view><view class="quick-grid"><view @tap="uni.redirectTo({url:'/pages/merchant/orders?status=1'})"><text>▣</text><small>待接单</small></view><view @tap="uni.redirectTo({url:'/pages/merchant/orders?type=1'})"><text>▤</text><small>堂食订单</small></view><view @tap="uni.redirectTo({url:'/pages/merchant/orders?type=2'})"><text>⌖</text><small>配送订单</small></view><view @tap="uni.redirectTo({url:'/pages/merchant/products'})"><text>▢</text><small>商品管理</small></view><view @tap="uni.navigateTo({url:'/pages/merchant/settings'})"><text>⚙</text><small>店铺设置</small></view></view><view class="card switches"><view class="between"><text>堂食服务</text><switch color="#34c759" :checked="shop.dineInStatus?.code===1" @change="toggle('dine-in-status',$event.detail.value)"/></view><view class="between"><text>配送服务</text><switch color="#34c759" :checked="shop.deliveryStatus?.code===1" @change="toggle('delivery-status',$event.detail.value)"/></view></view><view class="between section-head"><text class="section-title">新订单提醒</text><text class="brand" @tap="uni.redirectTo({url:'/pages/merchant/orders'})">查看全部 ›</text></view><OrderCard v-for="order in orders" :key="order.id" :order="order" merchant @open="open"/><view v-if="!orders.length" class="empty small-empty">暂无待接单订单</view></view><BottomNav active="dashboard" merchant/></view></template>
<style scoped>.business{display:flex;align-items:center;gap:12rpx;color:#666;font-size:22rpx}.date{margin:4rpx 0 18rpx;color:#666;font-size:23rpx}.overview{display:flex;gap:20rpx}.overview view{flex:1;height:150rpx;padding:26rpx;border-radius:22rpx;background:#fff;box-shadow:0 2rpx 12rpx rgba(0,0,0,.04)}.overview text{display:block;color:#777;font-size:23rpx}.overview strong{display:block;margin-top:20rpx;font-size:38rpx}.status-grid{display:flex;margin:20rpx 0;padding:24rpx 8rpx;border-radius:22rpx;background:#fff}.status-grid view{flex:1;display:flex;flex-direction:column;align-items:center;gap:10rpx}.status-grid text{font-size:34rpx;font-weight:800}.status-grid small{color:#777;font-size:21rpx}.orange{color:#ff8a34}.yellow{color:#ffb020}.purple{color:#722ed1}.cyan{color:#13c2c2}.quick-grid{display:flex;justify-content:space-between;margin:20rpx 0;padding:24rpx 8rpx;border-radius:22rpx;background:#fff}.quick-grid view{display:flex;flex-direction:column;align-items:center;gap:10rpx}.quick-grid text{width:64rpx;height:64rpx;border-radius:18rpx;background:#fff2e8;color:#ff8a34;text-align:center;line-height:64rpx;font-size:34rpx}.quick-grid small{font-size:20rpx}.switches{padding:0 26rpx}.switches view{height:88rpx;border-bottom:2rpx solid #f2f2f2}.switches view:last-child{border:0}.section-head{margin:30rpx 0 18rpx}.section-head text:last-child{font-size:23rpx}.small-empty{padding:50rpx}</style>
