<script setup>
import{ref}from'vue';import{onLoad,onPullDownRefresh,onShow}from'@dcloudio/uni-app';import BottomNav from'../../components/BottomNav.vue';import OrderCard from'../../components/OrderCard.vue';import{api}from'../../api'
const orders=ref([]),status=ref(null),orderType=ref(null),keyword=ref('');const tabs=[{l:'全部',v:null},{l:'待接单',v:1},{l:'已接单',v:2},{l:'制作中',v:3},{l:'待取餐',v:4},{l:'配送中',v:5},{l:'已送达',v:6}]
onLoad(q=>{status.value=q.status?Number(q.status):null;orderType.value=q.type?Number(q.type):null});onShow(load);onPullDownRefresh(async()=>{await load();uni.stopPullDownRefresh()})
async function load(){try{const data=await api.merchantOrders({current:1,size:100,status:status.value||undefined,orderType:orderType.value||undefined,keyword:keyword.value||undefined});orders.value=data?.records||[]}catch(_){}}
async function choose(v){status.value=v;await load()}
function open(order){uni.navigateTo({url:`/pages/merchant/order-detail?id=${order.id}`})}
</script>
<template><view class="page page-with-nav"><view class="search"><text>⌕</text><input v-model="keyword" confirm-type="search" placeholder="订单号、手机号或用户昵称" @confirm="load"/><button @tap="load">搜索</button></view><view class="type-tabs"><text :class="{active:!orderType}" @tap="orderType=null;load()">全部</text><text :class="{active:orderType===1}" @tap="orderType=1;load()">堂食</text><text :class="{active:orderType===2}" @tap="orderType=2;load()">配送</text></view><scroll-view class="status-tabs" scroll-x><text v-for="tab in tabs" :key="String(tab.v)" :class="{active:status===tab.v}" @tap="choose(tab.v)">{{tab.l}}</text></scroll-view><view class="content"><OrderCard v-for="order in orders" :key="order.id" :order="order" merchant @open="open"/><view v-if="!orders.length" class="empty"><text class="empty-icon">▤</text>没有符合条件的订单</view></view><BottomNav active="orders" merchant/></view></template>
<style scoped>.search{margin:20rpx 28rpx;height:72rpx;padding-left:22rpx;display:flex;align-items:center;gap:12rpx;border-radius:36rpx;background:#fff;color:#999}.search input{flex:1;font-size:24rpx}.search button{height:60rpx;padding:0 28rpx;border-radius:30rpx;background:#ff8a34;color:#fff;font-size:23rpx;line-height:60rpx}.type-tabs{display:flex;margin:0 28rpx 18rpx;padding:6rpx;border-radius:30rpx;background:#eaeaea}.type-tabs text{flex:1;text-align:center;border-radius:24rpx;line-height:48rpx;color:#777;font-size:23rpx}.type-tabs .active{background:#fff;color:#ff8a34;font-weight:700}.status-tabs{height:82rpx;white-space:nowrap;background:#fff}.status-tabs text{position:relative;display:inline-block;padding:0 28rpx;line-height:82rpx;color:#777;font-size:23rpx}.status-tabs .active{color:#ff8a34;font-weight:700}.status-tabs .active::after{content:'';position:absolute;left:30rpx;right:30rpx;bottom:0;height:5rpx;background:#ff8a34}</style>
