<script setup>
import{computed,ref}from'vue';import{onLoad}from'@dcloudio/uni-app';import ProductImage from'../../components/ProductImage.vue';import StatusBadge from'../../components/StatusBadge.vue';import{api}from'../../api';import{dateTime,money}from'../../utils/format'
const id=ref(),order=ref(null);const delivery=computed(()=>order.value?.orderType?.code===2)
onLoad(q=>{id.value=q.id;load()});async function load(){try{order.value=await api.merchantOrder(id.value)}catch(_){}}
const primary=computed(()=>{const s=order.value?.status?.code;if(s===1)return{label:'接受订单',action:'accept'};if(s===2)return{label:'开始制作',action:'start-cooking'};if(s===3)return delivery.value?{label:'开始配送',action:'start-delivery'}:{label:'标记待取餐',action:'ready-for-pickup'};if(s===4&&!delivery.value)return{label:'完成订单',action:'complete'};if(s===5&&delivery.value)return{label:'标记已送达',action:'mark-delivered'};return null})
async function act(){if(!primary.value)return;uni.showModal({title:primary.value.label,content:`确定执行“${primary.value.label}”吗？`,success:async res=>{if(res.confirm){await api.orderAction(id.value,primary.value.action);uni.showToast({title:'操作成功'});await load()}}})}
function reject(){uni.showModal({title:'拒绝订单',editable:true,placeholderText:'请输入拒单原因',success:async res=>{if(res.confirm&&res.content?.trim()){await api.orderAction(id.value,'reject',{reason:res.content.trim()});uni.showToast({title:'已拒单'});await load()}}})}
</script>
<template><view v-if="order" class="page merchant-detail"><view class="head-card"><view class="between"><view><text class="no">#{{order.orderNo}}</text><text class="muted">{{dateTime(order.createTime)}} · {{order.orderType.description}}</text></view><StatusBadge :status="order.status"/></view></view><view class="content"><view class="card info"><text class="section-title">履约信息</text><view class="between"><text>用户</text><text>{{order.userNickname||order.contactName}}</text></view><view class="between"><text>联系电话</text><text>{{order.contactPhone}}</text></view><view class="between"><text>{{delivery?'配送地址':'桌号'}}</text><text>{{delivery?`${order.addressArea}${order.addressDetail}${order.addressHouseNumber||''}`:(order.noSeatYet?'暂未入座':order.tableNo)}}</text></view><view v-if="order.remark" class="remark">备注：{{order.remark}}</view></view><view class="card goods-card"><text class="section-title">商品清单</text><view v-for="item in order.items" :key="item.id" class="goods"><ProductImage :src="item.productImageUrl" :name="item.productName" size="92rpx"/><view><text>{{item.productName}}</text><small>{{[item.specificationName,item.tasteName].filter(Boolean).join(' · ')}}</small></view><text>×{{item.quantity}}</text><text>¥{{money(item.amount)}}</text></view><view class="total">共{{order.items.reduce((s,i)=>s+i.quantity,0)}}件商品　实付 <text>¥{{money(order.payAmount)}}</text></view></view><view class="card logs"><text class="section-title">状态记录</text><view v-for="log in order.statusLogs" :key="log.orderVersion"><text class="dot"></text><view><text>{{log.toStatus.description}}</text><small>{{dateTime(log.createTime)}} {{log.reason||''}}</small></view></view></view></view><view v-if="primary||order.status.code===1" class="bottom-actions"><button v-if="order.status.code===1" class="outline-btn danger-outline" @tap="reject">拒绝订单</button><button v-if="primary" class="primary-btn" @tap="act">{{primary.label}}</button></view></view></template>
<style scoped>.merchant-detail{padding-bottom:130rpx}.head-card{padding:30rpx;margin:24rpx 28rpx;border-radius:24rpx;background:linear-gradient(135deg,#fff8ef,#fff)}.head-card view>view:first-child{display:flex;flex-direction:column;gap:10rpx}.no{font-size:30rpx;font-weight:800}.info,.goods-card,.logs{padding:28rpx;margin-bottom:22rpx}.section-title{display:block;margin-bottom:18rpx}.info .between{padding:15rpx 0;color:#666;font-size:24rpx}.info .between text:last-child{max-width:65%;text-align:right;color:#222}.remark{margin-top:14rpx;padding:20rpx;border-radius:12rpx;background:#fff2e8;color:#9c5e28;font-size:24rpx}.goods{display:flex;align-items:center;gap:14rpx;padding:17rpx 0;border-top:2rpx solid #f3f3f3;font-size:23rpx}.goods>view{min-width:0;flex:1;display:flex;flex-direction:column}.goods small{margin-top:6rpx;color:#999}.total{text-align:right;margin-top:20rpx;font-size:24rpx}.total text{color:#ff6b18;font-size:32rpx;font-weight:800}.logs>view{display:flex;gap:18rpx;padding:14rpx 0}.logs .dot{width:18rpx;height:18rpx;margin-top:6rpx;border-radius:50%;background:#ff8a34}.logs>view>view{display:flex;flex-direction:column;gap:7rpx}.logs small{color:#999;font-size:21rpx}.bottom-actions{position:fixed;z-index:50;left:0;right:0;bottom:0;height:calc(112rpx + env(safe-area-inset-bottom));padding:16rpx 28rpx calc(16rpx + env(safe-area-inset-bottom));display:flex;justify-content:flex-end;gap:18rpx;background:#fff}.bottom-actions .primary-btn{width:260rpx}.bottom-actions .outline-btn{width:auto}</style>
