<script setup>
import{ref}from'vue';import{onPullDownRefresh,onShow}from'@dcloudio/uni-app';import BottomNav from'../../components/BottomNav.vue';import ProductImage from'../../components/ProductImage.vue';import{api}from'../../api';import{money}from'../../utils/format'
const products=ref([]),categories=ref([]),categoryId=ref(null),status=ref(null),keyword=ref('')
onShow(load);onPullDownRefresh(async()=>{await load();uni.stopPullDownRefresh()});async function load(){try{const[cats,data]=await Promise.all([api.merchantCategories(),api.merchantProducts({current:1,size:100,categoryId:categoryId.value||undefined,status:status.value??undefined,keyword:keyword.value||undefined})]);categories.value=cats;products.value=data?.records||[]}catch(_){}}
function edit(id){uni.navigateTo({url:`/pages/merchant/product-edit${id?`?id=${id}`:''}`})}
async function action(item,name){try{if(name==='delete'){const res=await new Promise(resolve=>uni.showModal({title:'删除商品',content:`确定删除“${item.name}”吗？`,success:resolve}));if(!res.confirm)return;await api.deleteProduct(item.id)}else await api.productAction(item.id,name);uni.showToast({title:'操作成功'});await load()}catch(_){}}
</script>
<template><view class="page page-with-nav products-page"><view class="search"><input v-model="keyword" placeholder="搜索商品名称" confirm-type="search" @confirm="load"/><button @tap="load">搜索</button></view><scroll-view class="cats" scroll-x><text :class="{active:!categoryId}" @tap="categoryId=null;load()">全部</text><text v-for="cat in categories" :key="cat.id" :class="{active:categoryId===cat.id}" @tap="categoryId=cat.id;load()">{{cat.name}}</text></scroll-view><view class="status-tabs"><text :class="{active:status===null}" @tap="status=null;load()">全部</text><text :class="{active:status===1}" @tap="status=1;load()">销售中</text><text :class="{active:status===0}" @tap="status=0;load()">已下架</text><text :class="{active:status===2}" @tap="status=2;load()">已售罄</text></view><view class="content"><view v-for="item in products" :key="item.id" class="card product"><ProductImage :src="item.imageUrl" :name="item.name" size="132rpx"/><view class="info"><view class="between"><text class="name ellipsis">{{item.name}}</text><text class="status" :class="`s${item.status.code}`">{{item.status.description}}</text></view><text class="muted">{{item.categoryName}} · 库存 {{item.stock}}</text><text class="price">¥{{money(item.price)}}</text><view class="actions"><text @tap="edit(item.id)">编辑</text><text v-if="item.status.code!==1" @tap="action(item,'on-sale')">上架</text><text v-if="item.status.code===1" @tap="action(item,'off-sale')">下架</text><text v-if="item.status.code!==2" @tap="action(item,'sold-out')">售罄</text><text class="danger" @tap="action(item,'delete')">删除</text></view></view></view><view v-if="!products.length" class="empty"><text class="empty-icon">▢</text>暂无商品</view></view><button class="add" @tap="edit(null)">＋</button><BottomNav active="products" merchant/></view></template>
<style scoped>.products-page{padding-top:1rpx}.search{margin:18rpx 28rpx;height:72rpx;padding-left:24rpx;display:flex;border-radius:36rpx;background:#fff}.search input{flex:1;font-size:24rpx}.search button{height:60rpx;margin:6rpx;padding:0 28rpx;border-radius:30rpx;background:#ff8a34;color:#fff;font-size:23rpx;line-height:60rpx}.cats{height:76rpx;white-space:nowrap;background:#fff}.cats text{display:inline-block;padding:0 28rpx;line-height:76rpx;color:#666;font-size:23rpx}.cats .active{color:#ff8a34;font-weight:700}.status-tabs{display:flex;padding:14rpx 28rpx;background:#fff;border-top:2rpx solid #f2f2f2}.status-tabs text{flex:1;text-align:center;line-height:52rpx;color:#777;font-size:22rpx}.status-tabs .active{border-radius:26rpx;background:#fff2e8;color:#ff8a34}.product{display:flex;gap:20rpx;margin-bottom:20rpx;padding:22rpx}.info{min-width:0;flex:1}.name{max-width:260rpx;font-weight:800}.status{padding:5rpx 12rpx;border-radius:10rpx;font-size:20rpx}.s1{background:#f6ffed;color:#34c759}.s0{background:#f5f5f5;color:#999}.s2{background:#fff1f0;color:#ff4d4f}.info>.muted,.info>.price{display:block;margin-top:9rpx;font-size:22rpx}.actions{display:flex;justify-content:flex-end;gap:22rpx;margin-top:14rpx;color:#ff8a34;font-size:22rpx}.actions .danger{color:#ff4d4f}.add{position:fixed;z-index:85;right:32rpx;bottom:calc(135rpx + env(safe-area-inset-bottom));width:92rpx;height:92rpx;padding:0;border-radius:50%;background:#ff8a34;color:#fff;box-shadow:0 8rpx 25rpx rgba(255,138,52,.4);font-size:48rpx;line-height:88rpx}</style>
