<script setup>
import{ref}from'vue';import{onLoad}from'@dcloudio/uni-app';import ProductImage from'../../components/ProductImage.vue';import{api}from'../../api';import{BASE_URL,imageUrl}from'../../api/request'
const id=ref(null),categories=ref([]),saving=ref(false),specText=ref(''),tasteText=ref('');const form=ref({categoryId:null,name:'',imageUrl:'',description:'',detail:'',price:'',originalPrice:null,stock:0,status:1,recommended:false,specifications:[],tastes:[]})
onLoad(async q=>{id.value=q.id||null;try{categories.value=await api.merchantCategories();if(id.value){const data=await api.merchantProduct(id.value);form.value={...data,categoryId:data.categoryId,status:data.status.code,specifications:data.specifications||[],tastes:data.tastes||[]};specText.value=form.value.specifications.map(i=>`${i.name}:${i.priceDelta}`).join(',');tasteText.value=form.value.tastes.map(i=>i.name).join(',')}else form.value.categoryId=categories.value[0]?.id||null}catch(_){}})
function chooseImage(){uni.chooseImage({count:1,success:res=>{uni.showLoading({title:'上传中'});uni.uploadFile({url:`${BASE_URL}/api/merchant/files/images`,filePath:res.tempFilePaths[0],name:'file',header:{Authorization:`Bearer ${uni.getStorageSync('merchantToken')}`},success:r=>{try{const body=JSON.parse(r.data);if(body.code===0)form.value.imageUrl=body.data.url;else uni.showToast({title:body.message||'上传失败',icon:'none'})}catch(_){uni.showToast({title:'上传失败',icon:'none'})}},complete:()=>uni.hideLoading()})}})}
function options(){form.value.specifications=specText.value.split(',').map(v=>v.trim()).filter(Boolean).map((v,index)=>{const[name,delta='0']=v.split(':');const old=form.value.specifications.find(i=>i.name===name);return{id:old?.id,name,priceDelta:Number(delta)||0,status:1,sort:(index+1)*10}});form.value.tastes=tasteText.value.split(',').map(v=>v.trim()).filter(Boolean).map((name,index)=>{const old=form.value.tastes.find(i=>i.name===name);return{id:old?.id,name,status:1,sort:(index+1)*10}})}
async function save(){if(!form.value.categoryId||!form.value.name.trim()||!form.value.imageUrl||Number(form.value.price)<=0)return uni.showToast({title:'请完整填写分类、名称、图片和价格',icon:'none'});options();saving.value=true;try{const payload={...form.value,price:Number(form.value.price),originalPrice:form.value.originalPrice?Number(form.value.originalPrice):null,stock:Number(form.value.stock),detail:form.value.detail||null,description:form.value.description||null};await api.saveProduct(payload,id.value);uni.showToast({title:'保存成功'});setTimeout(()=>uni.navigateBack(),700)}catch(_){saving.value=false}}
</script>
<template><view class="page edit-page"><view class="content"><view class="card form-card"><view class="field image-field"><text class="field-label">商品图片 *</text><view @tap="chooseImage"><ProductImage :src="form.imageUrl" :name="form.name" size="200rpx"/><text>点击上传</text></view><text v-if="form.imageUrl" class="url ellipsis">{{imageUrl(form.imageUrl)}}</text></view><view class="field"><text class="field-label">商品名称 *</text><input v-model="form.name" class="input" maxlength="100" placeholder="请输入商品名称"/></view><view class="field"><text class="field-label">所属分类 *</text><picker :range="categories" range-key="name" @change="form.categoryId=categories[$event.detail.value].id"><view class="input picker">{{categories.find(i=>i.id===form.categoryId)?.name||'请选择分类'}} ›</view></picker></view><view class="two"><view class="field"><text class="field-label">现价 *</text><input v-model="form.price" class="input" type="digit" placeholder="0.00"/></view><view class="field"><text class="field-label">原价</text><input v-model="form.originalPrice" class="input" type="digit" placeholder="可不填"/></view></view><view class="field"><text class="field-label">库存 *</text><input v-model="form.stock" class="input" type="number"/></view><view class="field"><text class="field-label">商品简介</text><input v-model="form.description" class="input" maxlength="255" placeholder="一句话介绍商品"/></view><view class="field"><text class="field-label">规格（名称:加价，逗号分隔）</text><input v-model="specText" class="input" placeholder="小份:0,大份:5"/></view><view class="field"><text class="field-label">口味（逗号分隔）</text><input v-model="tasteText" class="input" placeholder="不辣,少辣,正常辣"/></view><view class="field"><text class="field-label">商品详情</text><textarea v-model="form.detail" class="textarea" maxlength="5000" placeholder="商品详细说明"/></view><view class="switch-row between"><text>上架销售</text><switch color="#34c759" :checked="form.status===1" @change="form.status=$event.detail.value?1:0"/></view><view class="switch-row between"><text>推荐商品</text><switch color="#ff8a34" :checked="form.recommended" @change="form.recommended=$event.detail.value"/></view></view></view><view class="save-bar"><button class="primary-btn" :disabled="saving" @tap="save">{{saving?'保存中…':'保存商品'}}</button></view></view></template>
<style scoped>.edit-page{padding-bottom:130rpx}.form-card{padding:28rpx}.image-field>view{display:flex;align-items:center;gap:20rpx;color:#ff8a34}.url{display:block;max-width:100%;margin-top:12rpx;color:#999;font-size:20rpx}.two{display:flex;gap:20rpx}.two .field{flex:1}.picker{line-height:88rpx}.switch-row{height:92rpx;border-top:2rpx solid #f2f2f2}.save-bar{position:fixed;left:0;right:0;bottom:0;padding:16rpx 28rpx calc(16rpx + env(safe-area-inset-bottom));background:#fff}.save-bar button{width:100%}</style>
